version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - db_data:/app/db_data
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Em produção real, você usaria o CMD do Dockerfile. Para simplicidade local,
    # runserver é suficiente. Para um deploy mais robusto com docker-compose:
    # command: waitress-serve --host 0.0.0.0 --port 8000 clinicmanager.wsgi:application

volumes:
  db_data:
  media_data: