# Generated by Django 4.2.24 on 2025-09-21 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=255)),
                ('nome_responsavel', models.CharField(blank=True, max_length=255)),
                ('data_nascimento', models.DateField()),
                ('laudo_medico', models.TextField(blank=True, verbose_name='Laudo Médico')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.grupo', verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='FichaTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico_paciente', models.TextField(blank=True)),
                ('observacoes_iniciais', models.TextField(blank=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='triagens/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_triagem', to='patients.patient')),
                ('terapeuta_autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='FichaEvolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('emoji_evolucao', models.CharField(choices=[('🟢😀', '🟢😀 Excelente'), ('🟡🙂', '🟡🙂 Bom'), ('⚪😐', '⚪😐 Neutro'), ('🔴😟', '🔴😟 Ruim'), ('🚨😢', '🚨😢 Péssimo')], default='⚪😐', max_length=10)),
                ('comentarios', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_evolucao', to='patients.patient')),
                ('terapeuta_autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_criadas', to='accounts.terapeuta')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField(blank=True)),
                ('historico_doenca_atual', models.TextField(blank=True)),
                ('outras_observacoes', models.TextField(blank=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anamneses/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='patients.patient')),
                ('terapeuta_autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.terapeuta')),
            ],
        ),
    ]
